# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ..models.base_model_ import Model
from .. import util


class ApiKeyObj(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, api_key: str=None):  # noqa: E501
        """ApiKeyObj - a model defined in Swagger

        :param api_key: The api_key of this ApiKeyObj.  # noqa: E501
        :type api_key: str
        """
        self.swagger_types = {
            'api_key': str
        }

        self.attribute_map = {
            'api_key': 'api_key'
        }

        self._api_key = api_key

    @classmethod
    def from_dict(cls, dikt) -> 'ApiKeyObj':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ApiKeyObj of this ApiKeyObj.  # noqa: E501
        :rtype: ApiKeyObj
        """
        return util.deserialize_model(dikt, cls)

    @property
    def api_key(self) -> str:
        """Gets the api_key of this ApiKeyObj.


        :return: The api_key of this ApiKeyObj.
        :rtype: str
        """
        return self._api_key

    @api_key.setter
    def api_key(self, api_key: str):
        """Sets the api_key of this ApiKeyObj.


        :param api_key: The api_key of this ApiKeyObj.
        :type api_key: str
        """
        if api_key is None:
            raise ValueError("Invalid value for `api_key`, must not be `None`")  # noqa: E501

        self._api_key = api_key
