# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ..models.base_model_ import Model
from .. import util


class CreateUrlObj(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, long_url: str=None, username: str=None, custom_alias: str=None, time_to_live: str=None):  # noqa: E501
        """CreateUrlObj - a model defined in Swagger

        :param long_url: The long_url of this CreateUrlObj.  # noqa: E501
        :type long_url: str
        :param username: The username of this CreateUrlObj.  # noqa: E501
        :type username: str
        :param custom_alias: The custom_alias of this CreateUrlObj.  # noqa: E501
        :type custom_alias: str
        :param time_to_live: The time_to_live of this CreateUrlObj.  # noqa: E501
        :type time_to_live: str
        """
        self.swagger_types = {
            'long_url': str,
            'username': str,
            'custom_alias': str,
            'time_to_live': str
        }

        self.attribute_map = {
            'long_url': 'long_url',
            'username': 'username',
            'custom_alias': 'custom_alias',
            'time_to_live': 'time_to_live'
        }

        self._long_url = long_url
        self._username = username
        self._custom_alias = custom_alias
        self._time_to_live = time_to_live

    @classmethod
    def from_dict(cls, dikt) -> 'CreateUrlObj':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CreateUrlObj of this CreateUrlObj.  # noqa: E501
        :rtype: CreateUrlObj
        """
        return util.deserialize_model(dikt, cls)

    @property
    def long_url(self) -> str:
        """Gets the long_url of this CreateUrlObj.


        :return: The long_url of this CreateUrlObj.
        :rtype: str
        """
        return self._long_url

    @long_url.setter
    def long_url(self, long_url: str):
        """Sets the long_url of this CreateUrlObj.


        :param long_url: The long_url of this CreateUrlObj.
        :type long_url: str
        """
        if long_url is None:
            raise ValueError("Invalid value for `long_url`, must not be `None`")  # noqa: E501

        self._long_url = long_url

    @property
    def username(self) -> str:
        """Gets the username of this CreateUrlObj.


        :return: The username of this CreateUrlObj.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username: str):
        """Sets the username of this CreateUrlObj.


        :param username: The username of this CreateUrlObj.
        :type username: str
        """

        self._username = username

    @property
    def custom_alias(self) -> str:
        """Gets the custom_alias of this CreateUrlObj.


        :return: The custom_alias of this CreateUrlObj.
        :rtype: str
        """
        return self._custom_alias

    @custom_alias.setter
    def custom_alias(self, custom_alias: str):
        """Sets the custom_alias of this CreateUrlObj.


        :param custom_alias: The custom_alias of this CreateUrlObj.
        :type custom_alias: str
        """

        self._custom_alias = custom_alias

    @property
    def time_to_live(self) -> str:
        """Gets the time_to_live of this CreateUrlObj.


        :return: The time_to_live of this CreateUrlObj.
        :rtype: str
        """
        return self._time_to_live

    @time_to_live.setter
    def time_to_live(self, time_to_live: str):
        """Sets the time_to_live of this CreateUrlObj.


        :param time_to_live: The time_to_live of this CreateUrlObj.
        :type time_to_live: str
        """

        self._time_to_live = time_to_live
