# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ..models.base_model_ import Model
from .. import util


class UpdatedUser(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, newpassword: str=None):  # noqa: E501
        """UpdatedUser - a model defined in Swagger

        :param newpassword: The newpassword of this UpdatedUser.  # noqa: E501
        :type newpassword: str
        """
        self.swagger_types = {
            'newpassword': str
        }

        self.attribute_map = {
            'newpassword': 'newpassword'
        }

        self._newpassword = newpassword

    @classmethod
    def from_dict(cls, dikt) -> 'UpdatedUser':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UpdatedUser of this UpdatedUser.  # noqa: E501
        :rtype: UpdatedUser
        """
        return util.deserialize_model(dikt, cls)

    @property
    def newpassword(self) -> str:
        """Gets the newpassword of this UpdatedUser.


        :return: The newpassword of this UpdatedUser.
        :rtype: str
        """
        return self._newpassword

    @newpassword.setter
    def newpassword(self, newpassword: str):
        """Sets the newpassword of this UpdatedUser.


        :param newpassword: The newpassword of this UpdatedUser.
        :type newpassword: str
        """
        if newpassword is None:
            raise ValueError("Invalid value for `newpassword`, must not be `None`")  # noqa: E501

        self._newpassword = newpassword
