ALLOWED_API_CALL_PER_MONTH = 100
USER='postgres'
PASSWORD='somePassword'
HOST='172.18.0.1'
PORT='5432'
DATABASE='shorturl'
SQLALCHEMY_DATABASE_URI = f'postgresql+psycopg2://{USER}:{PASSWORD}@{HOST}:{PORT}/{DATABASE}'